axodotdev/axoupdater

- src/lib.rs
Axo Releases come from the server in order of oldest to newest, which is the opposite of the order used by GitHub.
> fix(axo): fetch latest release

- src/lib.rs
This should help with debugging, rather than returning the underlying IO error.
> feat: return better error when receipt load fails

- README.md
- axoupdater-cli/Cargo.toml
- axoupdater-cli/src/bin/axoupdater/main.rs
- axoupdater/Cargo.toml
- axoupdater/src/lib.rs
Turns `run()` and `is_update_needed()` into asynchronous APIs by default, with synchronous APIs provided as alternatives.
> feat: use async APIs by default

- axoupdater/Cargo.toml
- axoupdater/src/lib.rs
Ensures it's no longer pulled in via gazenot/axo_releases.
> fix: tokio dep is non-default

- axoupdater-cli/src/bin/axoupdater/main.rs
- axoupdater/src/lib.rs
Returns old and new version info, plus the tag the new verson was built from.
Fixes #33.
> feat: return version info on success

- axoupdater/src/lib.rs
stdout/stderr can now be disabled via the `disable_installer_stdout()`/`disable_installer_stderr()` methods, or disabled together via the `disable_installer_output()` method.
Fixes #31.
> feat: allow disabling installer's output

- axoupdater/src/lib.rs
Compare the installation root of the previous version to the location the current executable is being run from. This is now part of the "should an update be performed" check.
Fixes #34.
> feat: check executable path is suitable

- axoupdater/src/lib.rs
This ensures cargo-dist's installer will place this in the desired location, however it was configured before. We use this to make sure the new version absolutely goes in the same place as the old one.
Depends on https://github.com/axodotdev/cargo-dist/pull/837.
> feat: use CARGO_DIST_FORCE_INSTALL_DIR

- Cargo.lock
- axoupdater/Cargo.toml
This reverts commit 58ba4f938a30f6a07a3048d878502d4501b413cf.
I was too aggressive about merging this; not all downstream users are ready to upgrade yet.
> Revert "chore(deps): bump reqwest from 0.11.27 to 0.12.0"

- Cargo.lock
- axoupdater-cli/Cargo.toml
- axoupdater-cli/src/bin/axoupdater/main.rs
- axoupdater/src/lib.rs
This adds the ability to install any version that exists for a package instead of just what's latest. By default, we still install the latest; installing specific versions can be requested by calls to `configure_version_specifier` before `run()`, as so:
```rust
updater.configure_version_specifier(UpdateRequest::Latest);
// or
updater.configure_version_specifier(UpdateRequest::SpecificTag("v0.12.0"));
// or
updater.configure_version_specifier(UpdateRequest::SpecificVersion("0.12.0"));
```
In order to meet the expectations of GitHub's API, this version specifier is a *tag* rather than a named version. If this turns out to be a problem, we do have alternatives that would involve enumerating releases on GitHub instead of requesting one version.
Testing instructions:
* Clone this repo
* Build …
> feat: install specific requested versions instead of latest

- Cargo.lock
- axoupdater-cli/Cargo.toml
- axoupdater-cli/tests/integration.rs
- axoupdater/src/lib.rs
This adds end-to-end integration tests for axoupdater-cli. It uses my cargodisttest repo, since it's a) set up for axoupdater already, and b) is in a known good state with its installer at the moment. I've added three core tests: one which upgrades from a version to whatever's the latest; one which upgrades to a specific version; and one which downgrades from the newest version to a specific earlier release.
There's some duplication here we could dedupe later, but it does work.
> tests: add axoupdater-cli integration tests

- axoupdater/src/lib.rs
This tries to cover for the case where Windows doesn't allow the currently-running EXE to be modified. We instead rename it into a temporary directory, and move it back to where it was if the update failed.
> feat: rename running EXE on Windows

- Cargo.lock
- axoupdater-cli/src/bin/axoupdater/main.rs
- axoupdater-cli/tests/integration.rs
- axoupdater/Cargo.toml
- axoupdater/src/lib.rs
* Require github tags to be parseable by axotag (or ignore the release)
* Provide a new LatestMaybePrerelease UpdateRequest mode
* Use Versions more freely in the code
* Prevent latest from downgrading
> feat(verhandle): properly provide versioned semantics

- axoupdater/Cargo.toml
- axoupdater/src/lib.rs
- axoupdater/src/test/helpers.rs
- axoupdater/src/test/mod.rs
This adds a new test helper module which is aimed not at axoupdater itself, but at external apps using it as a library. For example, cargo-dist uses this in order to perform a runtest of its self update command: https://github.com/axodotdev/cargo-dist/pull/913
This should work for any app which installs to `~/.cargo/bin`, but we should also consider making the install path configurable.
> feat: add test helpers

- axoupdater/src/lib.rs
Previously, a github api status error for the github releases page would show a confusing error message in uv:
```
$ uv self update
info: Checking for updates...
error: No releases were found for the app uv in workspace uv
```
I've tested this by manually updating the receipt to a non-existent repo:
```
$ uv self update
info: Checking for updates...
error: HTTP status client error (404 Not Found) for url (https://api.github.com/repos/astral-sh-borken/uv/releases)
```
Fixes #79
> Preserve reqwest error for the releases page

- axoupdater/src/lib.rs
Similar to the existing `set_version` method, this allows configuring the release source without reading it from a receipt. While the receipt is still necessary for actually performing the update, since it contains the install info we need to compare to, configuring the release source this way makes it possible to query for the latest version without loading a receipt.
> feat: manually configure release source

- axoupdater/src/lib.rs
This could be useful for apps (for example, to say "X version is available, would you like to update?") and also for testing.
> feat: API to query new version

- .github/workflows/ci.yml
- axoupdater-cli/src/bin/axoupdater/main.rs
- axoupdater/src/lib.rs
- axoupdater/src/release/github.rs
- axoupdater/src/release/mod.rs
These allow performing authorized requests with a higher rate limit, and which can access private repositories. The main intended usecase right now is our own tests, since they have a highly artificial environment where we run into rate limits more often than real-world users would.
> feat: allow configuring tokens to fetch releases

- axoupdater/src/lib.rs
This is another feature necessary for us to allow a "no receipt" mode, useful for people exercising axoupdater for first-time installs or as part of migrating from one updater to another.
> feat: allow configuring install prefix

- axoupdater/src/lib.rs
There are circumstances where it's useful to always install without comparing against the new release:
* Installations may be missing an install receipt for predictable reasons, for example when migrating from one updater to this library.
* An application may be using axoupdater in an "install if not present, otherwise upgrade" flow, in which case they wouldn't want to be comparing against the currently installed version.
Tests are currently missing; will add tomorrow.
> feat: "always" install strategy

- axoupdater-cli/tests/integration.rs
- axoupdater/src/lib.rs
- axoupdater/src/receipt.rs
We currently strip a trailing `/bin` directory in several places. This was done to work around a bug that shipped in cargo-dist between 0.10.0 and 0.12.0, where the prefix was always set to the `bin` directory instead of the actual install path. This was introduced in https://github.com/axodotdev/cargo-dist/commit/91ac6af587cf221b62d56c98cf99fb169c449011, which first shipped in 0.10.0, and finally eliminated in the install path rewrite that shipped in 0.12.0.
Always doing this actually introduced a few bugs of its own, so this now works around it by actually checking the version of the cargo-dist that produced the install receipt and only applying the correction if that version is within the 0.10.0 to pre-0.12.0 range. Luckily, we always included cargo-dist install info in the receipt …
> feat: tighten up `bin` subdir handling

- axoupdater/src/receipt.rs
This should only be stripped in the case that the true, normalized path itself doesn't end with `/bin`; there are cases where it might, such as if we're using the subdir path install method.
> fix: be more cautious about current_exe path

- axoupdater/src/lib.rs
`VersionReq` didn't treat prerelease versions within that range the way we expected; instead, just compare directly against the min and max versions.
> fix: compare against versions, not range

- Cargo.lock
- axoupdater-cli/Cargo.toml
- axoupdater-cli/tests/integration.rs
- axoupdater/Cargo.toml
- axoupdater/src/lib.rs
It's possible for the Windows tempdir to be on a different drive than the currently running EXE, which makes `rename()` impossible. In case that happens to us, we should handle it by creating the temp path to rename the Windows exe to inside the install prefix, a path that we should be able to trust to be a) writable to us, and b) on the same drive as the EXE itself.
If we don't know the install_prefix, fall back to the old behaviour of creating a temporary directory inside the system temp dir.
I had to migrate us to a different tempdir library to handle this, since `temp-dir` doesn't support creating temporary directories anywhere other than the system tmpdir.
Fixes #120.
> fix: avoid possible file rename across filesystem bounds on Windows

- Cargo.lock
- axoupdater-cli/Cargo.toml
- axoupdater/Cargo.toml
Updates axoasset and gazenot together since gazenot itself depends on axoasset, and this lets us update to a single version in-tree.
> chore: axoasset 0.10.1, gazenot 0.3.2

- axoupdater/src/lib.rs
Comparing against -installer.sh can get other installers in the same release. While the GitHub API methods filter to only releases that match what we want, the *asset* filtering was looser.
> fix: compare installer name more precisely

- axoupdater/src/errors.rs
- axoupdater/src/lib.rs
We print the stdout/stderr to the terminal by default, but if the caller has requested us to turn that off, we were instead throwing that output away. This now instead copies that output to the error type in the case that we didn't print it to the terminal, allowing the caller to try to do something with it.
I was undecided on whether we wanted to decode the strings before passing them on, or if we should just pass along the raw bytes we get from the process call.
> feat: return stdout/stderr from installers if able

- axoupdater-cli/src/bin/axoupdater/main.rs
This is primarily intended for use in debugging. I found it useful in testing #149.
> feat: allow overriding the installer path

- axoupdater/src/lib.rs
We're considering adding this to cargo-dist, and it could at some point become the only variable:
https://github.com/axodotdev/cargo-dist/issues/1375
> feat: support app-specific install dir config

- axoupdater-cli/tests/integration.rs
`cargo test` outside CI would end up adding the temporary directory persistently to user's real dotfiles. Leave this on in CI because it doesn't hurt anything there.
NOTE: this environment variable isn't supported on Windows at the moment - we should probably try to unify that behaviour.
Refs https://github.com/axodotdev/cargo-dist/issues/1374.
> tests: avoid modifying PATH outside CI

- axoupdater-cli/tests/integration.rs
We're adding support for a new, app-specific environment variable here which supercedes the old `INSTALLER_` one. Windows, which currently doesn't support this via the environment variable, will only support the app-specific one, so we need to make sure to add it.
This new environment variable is being added in https://github.com/axodotdev/cargo-dist/pull/1410.
> tests: add branded modify path var

- axoupdater/src/lib.rs
- axoupdater/src/receipt.rs
If the original installation was done via `APP_NAME_NO_MODIFY_PATH`, we should make sure the new installation does the same thing.
Fixes https://github.com/astral-sh/uv/issues/7319.
Fixes https://github.com/astral-sh/uv/issues/5576.
Fixes #174.
> feat: avoid modifying path if inappropriate

- Cargo.lock
- axoupdater/Cargo.toml
- axoupdater/src/errors.rs
- axoupdater/src/lib.rs
This is an attempt at handling https://github.com/axodotdev/cargo-dist/issues/1374 using the [self-replace crate](https://github.com/mitsuhiko/self-replace). We leave the existing Unix behaviour in place, since it's already safe, but it replaces the previous Windows version with a new one: the Windows EXE is given a specific temporary name and, if the upgrade succeeded, we then set a flag to ensure it's deleted once the process completes.
Appears to be working on Windows but needs more testing.
> feat: use self_replace to delete self

- Cargo.lock
- axoupdater/Cargo.toml
- axoupdater/src/release/github.rs
Resolves https://github.com/axodotdev/cargo-dist/issues/1449
> Allow changing the GitHub API base URL via the INSTALLER_DOWNLOAD_URL env var

- Cargo.lock
- axoupdater/Cargo.toml
- axoupdater/src/errors.rs
- axoupdater/src/lib.rs
- axoupdater/src/release/github.rs
These two new environment variables are defined for compatibility with cargo-dist, which uses the same variables in its installers: https://github.com/axodotdev/cargo-dist/pull/1503
> feat: use new custom env vars

- axoupdater/src/lib.rs
It'll be useful for us to be able to check the version of axoupdater we're using from dist.
> feat: export version

- dist-workspace.toml
I believe we can safely build this, and we should have binaries available for users who may want it. I've temporarily added `pr-run-mode = "upload"` to confirm.
> chore: add x86_64-pc-windows-gnu target

- axoupdater/src/lib.rs
We need access to this (or similar) to avoid confusion, e.g., https://github.com/astral-sh/uv/issues/6774#issuecomment-2504950681, when the receipt is for a different uv executable. See https://github.com/astral-sh/uv/pull/9487, which uses this change to power a message like:
```
❯ cargo run --all-features -q -- self update
warning: Self-update is only available for uv binaries installed via the standalone installation scripts.
The current executable is at `/Users/zb/workspace/uv/target/debug/uv` but the standalone installer was used to install uv to `/Users/zb/.cargo`. Are multiple copies of uv installed?
```
> Make `AxoUpdater::install_prefix_root` public

- axoupdater/src/lib.rs
- axoupdater/src/receipt.rs
This allows loading receipts that may exist under alternate app names. This is most useful if an app may have been renamed, and the older/newer versions use different naems from each other.
`load_receipt_as` doesn't change the internal name for the app, so it's safe to call multiple times with different names.
Edit: added a second method to make it possible to override the name that was parsed from a receipt.
> feat: allow loading alternate receipts

- axoupdater-cli/tests/integration.rs
- axoupdater/src/errors.rs
- axoupdater/src/receipt.rs
- axoupdater/src/test/helpers.rs
refs https://github.com/axodotdev/cargo-dist/pull/1355.
We'll need to make sure we ship the cargo-dist side as well when shipping this, so we don't get a mismatch in expectations.
An open question on this and the other PR: is it appropriate for us to respect this on both Linux and Mac? I'm assuming yes.
cc @brennanfee
> feat: support XDG_CONFIG_HOME for receipts

- Cargo.lock
- Cargo.toml
- axoupdater-cli/Cargo.toml
- axoupdater/src/test/helpers.rs
The receipt path refactors introduced a chicken-and-egg problem we need to resolve here.
> fix: fix runtest helper
