axodotdev/axoupdater

src/main.rs
The network request can be a little pokey.
=> feat: print when checking for updates

README.md
Adds a README with usage information.
=> docs: add a README

CHANGELOG.md, Cargo.lock, Cargo.toml, axoupdater-cli/Cargo.toml
Incorporates the new axoasset.
=> release: 0.3.1

axoupdater/src/lib.rs
This isn't guaranteed to actually be respected, but should be respected by installers produced with up-to-date cargo-dist as of the next release.
Fixes #40.
=> feat: provide install prefix in response

axoupdater/Cargo.toml
This should allow it to pick 0.11 or 0.12, as appropriate.
=> chore: relax reqwest range

axoupdater/src/lib.rs
Since we're subject to a tighter API request limit on GitHub, we can use this to perform one request instead of N requests, where N requests is the number of pages of releases in the history.
=> feat: support GitHub's /latest API

axoupdater/src/lib.rs
This is primarily useful for testing; it allows substituting a local copy of the installer in place of the installer from the new release.
=> feat: allow substitute installers

CHANGELOG.md, Cargo.lock, Cargo.toml, axoupdater-cli/Cargo.toml
This incorporates three recent PRs aimed at test environments.
=> release: 0.5.0

.github/workflows/ci.yml
The same change as https://github.com/axodotdev/cargo-dist/pull/922.
=> ci: set up cache key for OS

axoupdater/Cargo.toml
This should make the dep lighter for downstream crates.
=> chore: relax axoasset dep

axoupdater/src/lib.rs, axoupdater/src/release/mod.rs
This is used via the methods to explicitly set the current version.
=> feat: reexport Version

axoupdater/src/release/github.rs
fixes #105  this code is gross but should do the trick
=> fix(pagination): should be optional

CHANGELOG.md, Cargo.lock, Cargo.toml, axoupdater-cli/Cargo.toml
This incorporates the gazenot and axoasset updates.
=> release: 0.6.6

CHANGELOG.md, Cargo.lock, Cargo.toml, axoupdater-cli/Cargo.toml, axoupdater-cli/tests/integration.rs, axoupdater/Cargo.toml, axoupdater/src/errors.rs, axoupdater/src/lib.rs, axoupdater/src/release/github.rs
and update axoasset/gazenot to versions that support this
=> feat: add tls_native_roots feature

.github/workflows/release.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, axoupdater-cli/Cargo.toml
=> release: 0.6.9

CHANGELOG.md, Cargo.lock, Cargo.toml, axoupdater-cli/Cargo.toml
I didn't mention the test changes since those are purely internal.
=> release: 0.7.1

axoupdater/src/lib.rs
If the receipt points to a path that no longer exists, the call to canonicalize will blow up. In that case, we can fall back to the original path as listed in the receipt for safety.
=> fix: handle canonicalizing dead path

CHANGELOG.md, Cargo.lock, Cargo.toml, axoupdater-cli/Cargo.toml
It's a fairly minor bugfix but I'd like to get it out.
=> release: 0.7.2

axoupdater/src/lib.rs
While I calculated the new filename, I accidentally deleted the line that renames `self` to it.
=> fix: actually rename self

axoupdater/src/release/github.rs
Previously, when reconstructing the domain, we dropped the port completely.
=> fix: respect port in GitHub URLs

Cargo.lock, axoupdater-cli/Cargo.toml, axoupdater/Cargo.toml
* axoasset 1.3.0
* axocli 0.3.0
* axoprocess 0.3.1
* axotag 0.3.0
=> deps: bump axodeps
